### ISSUE TITLE
'Dataset' object has no attribute 'value'

### ISSUE THREAD

**Issue by JDFischbach** [stanfordnqp/maxwell-b#1]
When I try to run the bend90 example of spins-b with the Maxwell solver in 3D the Solver throws the following error:
```
Traceback (most recent call last):
  File "/home/jd/black/maxwell-b/maxwell-server/maxwell-solver/fdfd.py", line 324, in <module>
    simulate(sys.argv[1])  # Specify name of the job.
  File "/home/jd/black/maxwell-b/maxwell-server/maxwell-solver/fdfd.py", line 34, in simulate
    params = get_parameters(name)
  File "/home/jd/black/maxwell-b/maxwell-server/maxwell-solver/fdfd.py", line 204, in get_parameters
    bloch_phase = f['bloch_phase'].value
AttributeError: 'Dataset' object has no attribute 'value'
```

**Comment by JDFischbach** [comment]
I think this is caused by Dataset.value being removed from newer h5py libraries
